# This is a basic workflow to help you get started with Actions

name: Release

on:
  push:
    tags: [ "*.*.*" ]

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Placeholder for master branch
        run:
          echo "This job is a placeholder to ensure CI passes on master branch pushes and
          PRs. No image is built."

  release:
    strategy:
      matrix:
        #        os: [ ubuntu-latest, windows-latest, macos-latest ]
        os: [ windows-latest ]
    runs-on: ${{ matrix.os }}
    needs: build
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK & Gradle cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Gradle build
        run: |
          chmod +x ./gradlew
          ./gradlew jpackage

      - name: Zip jpackage output (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          # 压缩 Portable 版本
          Compress-Archive -Path build/jpackage/LicenseIssuerApp -DestinationPath build/LicenseIssuerApp-Portable.zip
          Copy-Item build/jpackage/LicenseIssuerAppInstaller-1.0.0.msi build/
          Copy-Item build/jpackage/LicenseIssuerAppInstaller-1.0.0.exe build/

      - name: Zip jpackage output (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          cd build/jpackage
          zip -r ../LicenseIssuerApp-Portable.zip LicenseIssuerApp
          cp LicenseIssuerAppInstaller-1.0.0.msi ../
          cp LicenseIssuerAppInstaller-1.0.0.exe ../

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          draft: false
          allowUpdates: true
          artifacts: |
            build/LicenseIssuerAppInstaller-1.0.0.msi
            build/LicenseIssuerAppInstaller-1.0.0.exe
            build/LicenseIssuerApp-Portable.zip
